"""Extract sections from a class-search results page.

CSUN's schedule pages are generated by PeopleSoft and their markup changes
between releases, so this parser keys off *column headings and field labels*
rather than CSS selectors. Any table whose headings look like a section list
is harvested, and card/definition-list layouts are handled by reading
``Label: value`` pairs. That survives a redesign in a way that
``div.psc_row > td:nth-child(4)`` does not.

Use :func:`describe_tables` when a page yields nothing -- it prints the
headings that were found so an unrecognised spelling can be added to
:data:`FIELD_SYNONYMS`.
"""

from __future__ import annotations

import re
from typing import Any, Iterable, Iterator

from bs4 import BeautifulSoup, Tag

from .models import Meeting, Section, Status, sort_sections
from .normalize import (
    clean,
    parse_course_id,
    parse_days,
    parse_instructors,
    parse_int,
    parse_meeting,
    parse_status,
    parse_time_range,
    parse_units,
)
from .terms import Term

# Canonical field -> heading/label substrings that mean it. Matching is done
# on lowercased, punctuation-stripped text, longest synonym first.
FIELD_SYNONYMS: dict[str, tuple[str, ...]] = {
    "class_number": ("class number", "class nbr", "class #", "classnum", "class no", "clsnbr"),
    "section": ("section number", "section", "sect", "seq"),
    "status": ("status", "availability", "enrollment status", "open/closed"),
    "seats_available": (
        "regular seats available", "seats available", "available seats",
        "seats open", "open seats", "seats remaining", "avail",
    ),
    "seats_capacity": ("enrollment capacity", "class capacity", "capacity", "enrl cap", "total seats"),
    "waitlist_available": ("waitlist seats available", "waitlist available", "waitlist open", "wait list available"),
    "waitlist_capacity": ("waitlist capacity", "waitlist total", "wait list capacity", "waitlist"),
    "meeting": ("days and times", "days & times", "days/times", "meeting time", "meeting pattern", "time", "schedule"),
    "days": ("days", "meeting days", "day"),
    "instruction_mode": ("instruction mode", "modality", "mode", "delivery", "format"),
    "instructors": ("instructor", "instructors", "faculty", "taught by"),
    "location": ("room", "location", "building", "where"),
    "units": ("units", "credits", "credit hours"),
    "title": ("class title", "course title", "title", "description"),
    "session": ("session", "term session"),
    "course": ("course", "catalog number", "course number", "subject and catalog", "class"),
    "dates": ("dates", "meeting dates", "start/end date"),
}

# A table is treated as a section list only if it exposes at least one of
# these -- otherwise every layout table on the page would be harvested.
_IDENTIFYING_FIELDS = {"class_number", "section", "status", "seats_available"}
_MIN_RECOGNISED_COLUMNS = 2

_COURSE_HEADING_RE = re.compile(r"\b([A-Z]{2,5})\s*[-_ ]?\s*(\d{1,3}[A-Z]{0,3})\b")
_LABEL_VALUE_RE = re.compile(r"^\s*([A-Za-z][A-Za-z /&#.]{2,40}?)\s*[:–-]\s*(.+?)\s*$")


def parse_sections(
    html: str,
    *,
    term: Term | None = None,
    source_url: str | None = None,
) -> list[Section]:
    """Parse every section found on a results page."""
    soup = _soup(html)
    sections: list[Section] = []

    for table in soup.find_all("table"):
        sections.extend(_sections_from_table(table, term=term, source_url=source_url))

    if not sections:
        sections.extend(_sections_from_labels(soup, term=term, source_url=source_url))

    return sort_sections(_dedupe(sections))


def describe_tables(html: str) -> list[dict[str, Any]]:
    """Report each table's headings and how they mapped -- a debugging aid."""
    soup = _soup(html)
    report = []
    for index, table in enumerate(soup.find_all("table")):
        headings = _header_cells(table)
        mapping = _map_columns(headings)
        report.append(
            {
                "index": index,
                "headings": headings,
                "recognised": {headings[i]: field for i, field in mapping.items() if i < len(headings)},
                "unrecognised": [h for i, h in enumerate(headings) if i not in mapping and h],
                "rows": max(len(table.find_all("tr")) - 1, 0),
                "used": _is_section_table(mapping),
            }
        )
    return report


# --------------------------------------------------------------------------
# table strategy
# --------------------------------------------------------------------------


def _sections_from_table(
    table: Tag, *, term: Term | None, source_url: str | None
) -> Iterator[Section]:
    headings = _header_cells(table)
    columns = _map_columns(headings)
    if not _is_section_table(columns):
        return

    context_subject, context_catalog, context_title = _course_context(table)

    for row in _data_rows(table):
        cells = row.find_all(["td", "th"])
        if not cells:
            continue

        values: dict[str, str] = {}
        for index, cell in enumerate(cells):
            field = columns.get(index)
            if not field:
                continue
            text = _cell_text(cell)
            # Multiple columns can map to the same field (e.g. two "days"
            # columns for a lecture/lab pair); keep the first non-empty.
            if text and not values.get(field):
                values[field] = text

        if not values:
            continue

        section = _build_section(
            values,
            term=term,
            source_url=source_url,
            fallback_subject=context_subject,
            fallback_catalog=context_catalog,
            fallback_title=context_title,
        )
        if section is not None:
            yield section


def _header_cells(table: Tag) -> list[str]:
    """Heading text for each column, from ``<th>`` or the first row."""
    header_row = table.find("tr", recursive=True)
    for row in table.find_all("tr"):
        if row.find("th"):
            header_row = row
            break
    if header_row is None:
        return []
    return [_cell_text(cell) for cell in header_row.find_all(["th", "td"])]


def _data_rows(table: Tag) -> Iterator[Tag]:
    """Every row after the heading row."""
    rows = table.find_all("tr")
    body = table.find("tbody")
    if body is not None and body.find_all("tr"):
        rows = body.find_all("tr")
        if rows and rows[0].find("th"):
            rows = rows[1:]
        return iter(rows)

    seen_header = False
    remaining = []
    for row in rows:
        if not seen_header and (row.find("th") or row is rows[0]):
            seen_header = True
            continue
        remaining.append(row)
    return iter(remaining)


def _map_columns(headings: Iterable[str]) -> dict[int, str]:
    """Column index -> canonical field name."""
    mapping: dict[int, str] = {}
    for index, heading in enumerate(headings):
        field = match_field(heading)
        if field:
            mapping[index] = field
    return mapping


def match_field(label: str | None) -> str | None:
    """Resolve a heading or label to a canonical field name."""
    text = _normalise_label(label)
    if not text:
        return None

    best: tuple[int, str] | None = None
    for field, synonyms in FIELD_SYNONYMS.items():
        for synonym in synonyms:
            if text == synonym or synonym in text:
                score = len(synonym) + (100 if text == synonym else 0)
                if best is None or score > best[0]:
                    best = (score, field)
    return best[1] if best else None


def _is_section_table(columns: dict[int, str]) -> bool:
    fields = set(columns.values())
    return bool(fields & _IDENTIFYING_FIELDS) and len(fields) >= _MIN_RECOGNISED_COLUMNS


def _course_context(table: Tag) -> tuple[str | None, str | None, str | None]:
    """Find the ``COMP 586 - Title`` heading this table sits under."""
    node: Tag | None = table
    while node is not None:
        for previous in node.find_all_previous(
            ["h1", "h2", "h3", "h4", "h5", "caption", "summary", "legend", "strong", "a"], limit=40
        ):
            text = clean(previous.get_text(" ", strip=True))
            if not text or len(text) > 200:
                continue
            match = _COURSE_HEADING_RE.search(text.upper())
            if match:
                title = clean(re.sub(r".*?[-–:]\s*", "", text, count=1)) if "-" in text or "–" in text else None
                return match.group(1), match.group(2), title
        node = node.parent if isinstance(node.parent, Tag) else None
        if node is not None and node.name in ("body", "html"):
            break
    return None, None, None


# --------------------------------------------------------------------------
# label/value strategy (card layouts, PeopleSoft detail panes)
# --------------------------------------------------------------------------


def _sections_from_labels(
    soup: BeautifulSoup, *, term: Term | None, source_url: str | None
) -> list[Section]:
    sections = []
    for container in _candidate_containers(soup):
        values = _label_values(container)
        if not (set(values) & _IDENTIFYING_FIELDS):
            continue
        subject, catalog = parse_course_id(values.get("course"))
        if subject is None:
            heading = container.find(["h1", "h2", "h3", "h4", "strong"])
            subject, catalog = parse_course_id(heading.get_text(" ", strip=True) if heading else None)
        section = _build_section(
            values,
            term=term,
            source_url=source_url,
            fallback_subject=subject,
            fallback_catalog=catalog,
            fallback_title=None,
        )
        if section is not None:
            sections.append(section)
    return sections


def _candidate_containers(soup: BeautifulSoup) -> Iterator[Tag]:
    """Blocks that plausibly describe one section each."""
    for tag in soup.find_all(["li", "article", "section", "div", "dl"]):
        # Skip wrappers that contain other candidates -- we want leaf-ish blocks.
        if tag.find(["li", "article", "dl"], recursive=True):
            continue
        text = tag.get_text(" ", strip=True)
        if 20 < len(text) < 2000:
            yield tag


def _label_values(container: Tag) -> dict[str, str]:
    """Read ``Label: value`` pairs, including ``<dt>``/``<dd>`` and cells."""
    values: dict[str, str] = {}

    for dt in container.find_all("dt"):
        dd = dt.find_next_sibling("dd")
        if dd is None:
            continue
        field = match_field(dt.get_text(" ", strip=True))
        if field and not values.get(field):
            values[field] = _cell_text(dd)

    for node in container.find_all(string=True):
        match = _LABEL_VALUE_RE.match(str(node))
        if not match:
            continue
        field = match_field(match.group(1))
        value = clean(match.group(2))
        if field and value and not values.get(field):
            values[field] = value

    return values


# --------------------------------------------------------------------------
# assembly
# --------------------------------------------------------------------------


def _build_section(
    values: dict[str, str],
    *,
    term: Term | None,
    source_url: str | None,
    fallback_subject: str | None,
    fallback_catalog: str | None,
    fallback_title: str | None,
) -> Section | None:
    subject, catalog = parse_course_id(values.get("course"))
    subject = subject or fallback_subject
    catalog = catalog or fallback_catalog
    if not subject or not catalog:
        return None

    class_number = _digits(values.get("class_number"), width=5)
    section_id = clean(values.get("section"))
    if section_id and not class_number and re.fullmatch(r"\d{5}", section_id):
        # Some layouts put the five-digit class number in a "Section" column.
        class_number, section_id = section_id, None

    status = parse_status(values.get("status"))
    seats = parse_int(values.get("seats_available"))
    if status is Status.UNKNOWN and seats is not None:
        status = Status.OPEN if seats > 0 else Status.CLOSED

    meetings = _build_meetings(values)

    return Section(
        subject=subject,
        catalog_number=catalog,
        class_number=class_number,
        section=section_id,
        title=clean(values.get("title")) or fallback_title,
        status=status,
        seats_available=seats,
        seats_capacity=parse_int(values.get("seats_capacity")),
        waitlist_available=parse_int(values.get("waitlist_available")),
        waitlist_capacity=parse_int(values.get("waitlist_capacity")),
        units=parse_units(values.get("units")),
        instruction_mode=clean(values.get("instruction_mode")),
        instructors=parse_instructors(values.get("instructors")),
        meetings=meetings,
        session=clean(values.get("session")),
        term=term,
        source_url=source_url,
        raw=dict(values),
    )


def _build_meetings(values: dict[str, str]) -> tuple[Meeting, ...]:
    """Assemble meetings from either a combined column or split day/time ones."""
    location = clean(values.get("location"))
    combined = clean(values.get("meeting"))
    days_text = clean(values.get("days"))

    if combined and not (days_text and _looks_like_time_only(combined)):
        meeting = parse_meeting(combined, location)
        return (meeting,) if meeting else ()

    if days_text or combined:
        days = parse_days(days_text)
        start, end = parse_time_range(combined)
        if days or start or location:
            return (Meeting(days=days, start=start, end=end, location=location),)

    return (Meeting(location=location),) if location else ()


def _looks_like_time_only(text: str) -> bool:
    """True for ``"7:00PM-8:15PM"`` -- a time range with no day letters."""
    return bool(re.search(r"\d", text)) and not parse_days(re.sub(r"[\d:apmAPM.\s\-–—]", "", text))


def _digits(value: str | None, *, width: int | None = None) -> str | None:
    if value is None:
        return None
    match = re.search(rf"\d{{{width}}}" if width else r"\d+", value)
    if match:
        return match.group()
    fallback = re.search(r"\d+", value)
    return fallback.group() if fallback else None


def _cell_text(cell: Tag) -> str:
    """Cell text, falling back to image alt/title -- PeopleSoft draws status
    as a green/blue dot with the word in ``alt``."""
    text = clean(cell.get_text(" ", strip=True))
    if text:
        return text
    for image in cell.find_all("img"):
        alt = clean(image.get("alt") or image.get("title"))
        if alt:
            return alt
    return ""


def _normalise_label(label: str | None) -> str:
    if not label:
        return ""
    text = label.replace("\xa0", " ").lower()
    text = re.sub(r"[^a-z0-9&#/ ]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def _dedupe(sections: Iterable[Section]) -> list[Section]:
    """Drop repeats -- nested tables can surface the same row twice."""
    seen: set[tuple] = set()
    unique = []
    for section in sections:
        key = (
            section.subject,
            section.catalog_number,
            section.class_number,
            section.section,
            section.meeting_pattern,
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(section)
    return unique


def _soup(html: str) -> BeautifulSoup:
    try:
        return BeautifulSoup(html, "lxml")
    except Exception:  # lxml is optional
        return BeautifulSoup(html, "html.parser")
