import type { Broadcaster } from '../types';

export const BROADCASTERS: Record<string, Broadcaster> = {
  'sky-sports': {
    id: 'sky-sports',
    name: 'Sky Sports',
    shortName: 'Sky',
    type: 'tv',
    country: 'UK',
    color: '#0085ca',
    isFree: false,
  },
  'sky-sports-f1': {
    id: 'sky-sports-f1',
    name: 'Sky Sports F1',
    shortName: 'Sky F1',
    type: 'tv',
    country: 'UK',
    color: '#0085ca',
    isFree: false,
  },
  'sky-sports-pl': {
    id: 'sky-sports-pl',
    name: 'Sky Sports Premier League',
    shortName: 'Sky PL',
    type: 'tv',
    country: 'UK',
    color: '#0085ca',
    isFree: false,
  },
  'sky-sports-main': {
    id: 'sky-sports-main',
    name: 'Sky Sports Main Event',
    shortName: 'Sky Main',
    type: 'tv',
    country: 'UK',
    color: '#0085ca',
    isFree: false,
  },
  'tnt-sports': {
    id: 'tnt-sports',
    name: 'TNT Sports',
    shortName: 'TNT',
    type: 'tv',
    country: 'UK',
    color: '#ff6900',
    isFree: false,
  },
  'bbc-sport': {
    id: 'bbc-sport',
    name: 'BBC Sport',
    shortName: 'BBC',
    type: 'tv',
    country: 'UK',
    color: '#e4003b',
    isFree: true,
  },
  'bbc-one': {
    id: 'bbc-one',
    name: 'BBC One',
    shortName: 'BBC 1',
    type: 'tv',
    country: 'UK',
    color: '#e4003b',
    isFree: true,
  },
  'bbc-two': {
    id: 'bbc-two',
    name: 'BBC Two',
    shortName: 'BBC 2',
    type: 'tv',
    country: 'UK',
    color: '#e4003b',
    isFree: true,
  },
  'itv': {
    id: 'itv',
    name: 'ITV',
    shortName: 'ITV',
    type: 'tv',
    country: 'UK',
    color: '#f6a400',
    isFree: true,
  },
  'itv4': {
    id: 'itv4',
    name: 'ITV4',
    shortName: 'ITV4',
    type: 'tv',
    country: 'UK',
    color: '#f6a400',
    isFree: true,
  },
  'channel-4': {
    id: 'channel-4',
    name: 'Channel 4',
    shortName: 'C4',
    type: 'tv',
    country: 'UK',
    color: '#8e24aa',
    isFree: true,
  },
  'amazon-prime': {
    id: 'amazon-prime',
    name: 'Amazon Prime Video',
    shortName: 'Prime',
    type: 'streaming',
    color: '#00a8e0',
    isFree: false,
  },
  'dazn': {
    id: 'dazn',
    name: 'DAZN',
    shortName: 'DAZN',
    type: 'streaming',
    color: '#f8de00',
    isFree: false,
  },
  'discovery-plus': {
    id: 'discovery-plus',
    name: 'discovery+',
    shortName: 'D+',
    type: 'streaming',
    color: '#0097db',
    isFree: false,
  },
  'eurosport': {
    id: 'eurosport',
    name: 'Eurosport',
    shortName: 'Euro',
    type: 'tv',
    color: '#0097db',
    isFree: false,
  },
  'espn-plus': {
    id: 'espn-plus',
    name: 'ESPN+',
    shortName: 'ESPN+',
    type: 'streaming',
    country: 'US',
    color: '#d00027',
    isFree: false,
  },
  'peacock': {
    id: 'peacock',
    name: 'Peacock',
    shortName: 'Peacock',
    type: 'streaming',
    country: 'US',
    color: '#6438b0',
    isFree: false,
  },
  'apple-tv': {
    id: 'apple-tv',
    name: 'Apple TV+',
    shortName: 'Apple',
    type: 'streaming',
    color: '#555',
    isFree: false,
  },
  'max': {
    id: 'max',
    name: 'Max',
    shortName: 'Max',
    type: 'streaming',
    country: 'US',
    color: '#001eff',
    isFree: false,
  },
};

export const getBroadcaster = (id: string): Broadcaster =>
  BROADCASTERS[id] ?? { id, name: id, type: 'tv', isFree: false };

export const getBroadcasters = (ids: string[]): Broadcaster[] =>
  ids.map(getBroadcaster);
