import type { SportEvent } from '../types';
import { getBroadcasters } from './broadcasters';

// All timestamps are UTC. Base date: 2026-06-11 (Thursday)
// t() produces an ISO string offset from a base date by hours
function t(dateStr: string, hour: number, min = 0): string {
  const d = new Date(`${dateStr}T00:00:00Z`);
  d.setUTCHours(hour, min, 0, 0);
  return d.toISOString();
}

function end(start: string, durationHours: number): string {
  const d = new Date(start);
  d.setTime(d.getTime() + durationHours * 60 * 60 * 1000);
  return d.toISOString();
}

const NOW = new Date();
export const MODULE_LOAD_TIME = NOW.getTime();
function fromNow(offsetMinutes: number): string {
  const d = new Date(NOW.getTime() + offsetMinutes * 60 * 1000);
  return d.toISOString();
}

export const MOCK_EVENTS: SportEvent[] = [
  // ──────────────── LIVE NOW ────────────────
  {
    id: 'f1-canada-fp2-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'f1',
    league: 'Formula 1 World Championship',
    competition: 'Canadian Grand Prix',
    eventTitle: 'Canadian GP — Free Practice 2',
    participants: [],
    stage: 'Free Practice 2',
    startTimeUtc: fromNow(-45),
    endTimeUtc: fromNow(45),
    status: 'live',
    isLive: true,
    venue: 'Circuit Gilles Villeneuve, Montreal',
    country: 'Canada',
    broadcasters: getBroadcasters(['sky-sports-f1', 'channel-4']),
    streamingPlatforms: ['sky-sports-f1'],
    tvChannels: ['Sky Sports F1', 'Channel 4'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports F1'], streamingPlatforms: ['sky-sports-f1'] },
      { region: 'US', country: 'US', broadcasters: ['ESPN+'], streamingPlatforms: ['espn-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['f1', 'free-practice', 'weekend', 'live'],
    seriesId: 'f1-canada-2026',
    sessionType: 'practice',
    isFeatured: true,
    importance: 'medium',
  },
  {
    id: 'cricket-eng-ind-test2-day1',
    source: 'mock',
    sourcePriority: 1,
    sport: 'cricket',
    league: 'International Cricket',
    competition: 'England vs India Test Series',
    eventTitle: 'England vs India — 2nd Test, Day 1',
    participants: [
      { name: 'England', shortName: 'ENG', nationality: 'England', isHome: true },
      { name: 'India', shortName: 'IND', nationality: 'India' },
    ],
    stage: 'Day 1',
    startTimeUtc: fromNow(-120),
    endTimeUtc: fromNow(240),
    status: 'live',
    isLive: true,
    venue: "Headingley, Leeds",
    country: 'England',
    broadcasters: getBroadcasters(['sky-sports', 'channel-4']),
    streamingPlatforms: ['sky-sports'],
    tvChannels: ['Sky Sports Cricket'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Cricket'], streamingPlatforms: ['sky-sports'] },
      { region: 'India', country: 'IN', broadcasters: ['Star Sports'], streamingPlatforms: [], isGeolocked: true },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['cricket', 'test', 'international', 'ashes-series', 'live'],
    sessionType: 'test',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'tennis-atp-queens-sf1',
    source: 'mock',
    sourcePriority: 1,
    sport: 'tennis',
    league: 'ATP Tour',
    competition: "cinch Championships (Queen's Club)",
    eventTitle: "Djokovic vs Alcaraz — SF (Queen's Club)",
    participants: [
      { name: 'Novak Djokovic', shortName: 'Djokovic', nationality: 'Serbia', rank: 3 },
      { name: 'Carlos Alcaraz', shortName: 'Alcaraz', nationality: 'Spain', rank: 2 },
    ],
    stage: 'Semi-Final',
    startTimeUtc: fromNow(-30),
    endTimeUtc: fromNow(120),
    status: 'live',
    isLive: true,
    venue: "Queen's Club, London",
    country: 'England',
    broadcasters: getBroadcasters(['amazon-prime', 'discovery-plus']),
    streamingPlatforms: ['amazon-prime'],
    tvChannels: [],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Amazon Prime Video'], streamingPlatforms: ['amazon-prime'] },
      { region: 'US', country: 'US', broadcasters: ['Tennis Channel'], streamingPlatforms: [], isGeolocked: true },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['tennis', 'atp', 'queens', 'grass-court', 'wimbledon-prep', 'live'],
    sessionType: 'semi-final',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'golf-us-open-rd1-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'golf',
    league: 'US Open Golf',
    competition: 'US Open Championship 2026',
    eventTitle: 'US Open — Round 1',
    participants: [],
    stage: 'Round 1',
    startTimeUtc: fromNow(-180),
    endTimeUtc: fromNow(300),
    status: 'live',
    isLive: true,
    venue: 'Pinehurst Resort No. 2, North Carolina',
    country: 'US',
    broadcasters: getBroadcasters(['sky-sports', 'bbc-sport', 'channel-4']),
    streamingPlatforms: ['peacock'],
    tvChannels: ['Sky Sports Golf', 'BBC Sport'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Golf', 'BBC Sport'], streamingPlatforms: ['sky-sports'] },
      { region: 'US', country: 'US', broadcasters: ['Peacock', 'NBC'], streamingPlatforms: ['peacock'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['golf', 'major', 'us-open', 'live'],
    sessionType: 'other',
    isFeatured: true,
    importance: 'high',
  },

  // ──────────────── UP NEXT (within 3h) ────────────────
  {
    id: 'nba-finals-g5-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'basketball',
    league: 'NBA',
    competition: 'NBA Finals 2026',
    eventTitle: 'Oklahoma City Thunder vs Boston Celtics — Finals Game 5',
    participants: [
      { name: 'Oklahoma City Thunder', shortName: 'OKC', isHome: false },
      { name: 'Boston Celtics', shortName: 'BOS', isHome: true },
    ],
    stage: 'NBA Finals — Game 5',
    startTimeUtc: fromNow(90),
    endTimeUtc: fromNow(210),
    status: 'upcoming',
    isLive: false,
    venue: 'TD Garden, Boston, MA',
    country: 'US',
    broadcasters: getBroadcasters(['bbc-two', 'sky-sports-main']),
    streamingPlatforms: ['amazon-prime'],
    tvChannels: ['Sky Sports Action', 'BBC Two (highlights)'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Action'], streamingPlatforms: ['sky-sports'] },
      { region: 'US', country: 'US', broadcasters: ['ABC'], streamingPlatforms: ['espn-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['basketball', 'nba', 'finals', 'championship', 'soon'],
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'football-euro2026-qf1',
    source: 'mock',
    sourcePriority: 1,
    sport: 'football',
    league: 'UEFA Euro 2028 Qualifying',
    competition: 'UEFA Nations League Final',
    eventTitle: 'Spain vs Germany — UEFA Nations League Final',
    participants: [
      { name: 'Spain', shortName: 'ESP', nationality: 'Spain' },
      { name: 'Germany', shortName: 'GER', nationality: 'Germany' },
    ],
    stage: 'Final',
    startTimeUtc: fromNow(150),
    endTimeUtc: fromNow(270),
    status: 'upcoming',
    isLive: false,
    venue: 'Allianz Arena, Munich',
    country: 'Germany',
    broadcasters: getBroadcasters(['bbc-one', 'channel-4']),
    streamingPlatforms: ['bbc-sport'],
    tvChannels: ['BBC One', 'Channel 4'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['BBC One'], streamingPlatforms: [], isFree: true } as { region: string; country: string; broadcasters: string[]; streamingPlatforms: string[]; isGeolocked?: boolean },
      { region: 'US', country: 'US', broadcasters: ['Paramount+'], streamingPlatforms: ['paramount-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['football', 'nations-league', 'final', 'international', 'free-to-air', 'soon'],
    sessionType: 'final',
    isFeatured: true,
    importance: 'high',
  },

  // ──────────────── TONIGHT ────────────────
  {
    id: 'ufc-311-prelims-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'ufc',
    league: 'UFC',
    competition: 'UFC 311',
    eventTitle: 'UFC 311: Makhachev vs Poirier — Prelims',
    participants: [],
    stage: 'Preliminary Card',
    startTimeUtc: fromNow(300),
    endTimeUtc: fromNow(420),
    status: 'upcoming',
    isLive: false,
    venue: 'Intuit Dome, Inglewood, CA',
    country: 'US',
    broadcasters: getBroadcasters(['tnt-sports']),
    streamingPlatforms: ['dazn'],
    tvChannels: ['TNT Sports 1'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['TNT Sports'], streamingPlatforms: ['dazn'] },
      { region: 'US', country: 'US', broadcasters: ['ESPN+'], streamingPlatforms: ['espn-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['ufc', 'mma', 'prelims', 'fight-night'],
    seriesId: 'ufc-311-2026',
    sessionType: 'prelims',
    relatedEventIds: ['ufc-311-main-2026'],
    importance: 'medium',
  },
  {
    id: 'ufc-311-main-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'ufc',
    league: 'UFC',
    competition: 'UFC 311',
    eventTitle: 'UFC 311: Makhachev vs Poirier — Main Card',
    participants: [
      { name: 'Islam Makhachev', shortName: 'Makhachev', nationality: 'Russia', rank: 1 },
      { name: 'Dustin Poirier', shortName: 'Poirier', nationality: 'US', rank: 3 },
    ],
    stage: 'Main Card — Lightweight Title',
    startTimeUtc: fromNow(420),
    endTimeUtc: fromNow(600),
    status: 'upcoming',
    isLive: false,
    venue: 'Intuit Dome, Inglewood, CA',
    country: 'US',
    broadcasters: getBroadcasters(['tnt-sports', 'dazn']),
    streamingPlatforms: ['dazn'],
    tvChannels: ['TNT Sports Box Office'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['TNT Sports Box Office'], streamingPlatforms: ['dazn'] },
      { region: 'US', country: 'US', broadcasters: ['ESPN+ PPV'], streamingPlatforms: ['espn-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['ufc', 'mma', 'main-card', 'title-fight', 'lightweight', 'big-tonight'],
    seriesId: 'ufc-311-2026',
    sessionType: 'main-card',
    relatedEventIds: ['ufc-311-prelims-2026'],
    isFeatured: true,
    importance: 'high',
  },

  // ──────────────── TOMORROW (Friday June 12) ────────────────
  {
    id: 'f1-canada-qualifying-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'f1',
    league: 'Formula 1 World Championship',
    competition: 'Canadian Grand Prix',
    eventTitle: 'Canadian GP — Qualifying',
    participants: [],
    stage: 'Qualifying',
    startTimeUtc: fromNow(24 * 60 + 60),
    endTimeUtc: fromNow(24 * 60 + 120),
    status: 'upcoming',
    isLive: false,
    venue: 'Circuit Gilles Villeneuve, Montreal',
    country: 'Canada',
    broadcasters: getBroadcasters(['sky-sports-f1', 'channel-4']),
    streamingPlatforms: ['sky-sports-f1'],
    tvChannels: ['Sky Sports F1', 'Channel 4'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports F1', 'Channel 4'], streamingPlatforms: ['sky-sports-f1'] },
      { region: 'US', country: 'US', broadcasters: ['ESPN+'], streamingPlatforms: ['espn-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['f1', 'qualifying', 'weekend', 'canada'],
    seriesId: 'f1-canada-2026',
    sessionType: 'qualifying',
    relatedEventIds: ['f1-canada-fp2-2026', 'f1-canada-race-2026'],
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'tennis-wta-eastbourne-qf',
    source: 'mock',
    sourcePriority: 1,
    sport: 'tennis',
    league: 'WTA Tour',
    competition: 'Eastbourne International',
    eventTitle: 'Sabalenka vs Swiatek — QF (Eastbourne)',
    participants: [
      { name: 'Aryna Sabalenka', shortName: 'Sabalenka', nationality: 'Belarus', rank: 1 },
      { name: 'Iga Swiatek', shortName: 'Swiatek', nationality: 'Poland', rank: 2 },
    ],
    stage: 'Quarter-Final',
    startTimeUtc: fromNow(24 * 60 + 180),
    endTimeUtc: fromNow(24 * 60 + 300),
    status: 'upcoming',
    isLive: false,
    venue: 'Devonshire Park, Eastbourne',
    country: 'England',
    broadcasters: getBroadcasters(['amazon-prime']),
    streamingPlatforms: ['amazon-prime'],
    tvChannels: [],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Amazon Prime Video'], streamingPlatforms: ['amazon-prime'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['tennis', 'wta', 'eastbourne', 'grass', 'wimbledon-prep'],
    sessionType: 'quarter-final',
    importance: 'high',
  },
  {
    id: 'boxing-kambosos-haney-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'boxing',
    league: 'Boxing',
    competition: 'WBC Lightweight Championship',
    eventTitle: 'Haney vs Garcia II — WBC Lightweight Title',
    participants: [
      { name: 'Devin Haney', shortName: 'Haney', nationality: 'US', rank: 1 },
      { name: 'Ryan Garcia', shortName: 'Garcia', nationality: 'US', rank: 5 },
    ],
    stage: 'Main Event',
    startTimeUtc: fromNow(24 * 60 + 360),
    status: 'upcoming',
    isLive: false,
    venue: 'MGM Grand Garden Arena, Las Vegas',
    country: 'US',
    broadcasters: getBroadcasters(['dazn']),
    streamingPlatforms: ['dazn'],
    tvChannels: [],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['DAZN'], streamingPlatforms: ['dazn'] },
      { region: 'US', country: 'US', broadcasters: ['DAZN'], streamingPlatforms: ['dazn'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['boxing', 'wbc', 'lightweight', 'title-fight', 'big-tonight'],
    sessionType: 'match',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'rugby-prem-final-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'rugby',
    league: 'Gallagher Premiership',
    competition: 'Gallagher Premiership Final',
    eventTitle: 'Sale Sharks vs Harlequins — Premiership Final',
    participants: [
      { name: 'Sale Sharks', shortName: 'Sale', nationality: 'England' },
      { name: 'Harlequins', shortName: 'Quins', nationality: 'England' },
    ],
    stage: 'Final',
    startTimeUtc: fromNow(24 * 60 + 210),
    endTimeUtc: fromNow(24 * 60 + 330),
    status: 'upcoming',
    isLive: false,
    venue: 'Allianz Stadium, Twickenham',
    country: 'England',
    broadcasters: getBroadcasters(['tnt-sports', 'channel-4']),
    streamingPlatforms: ['discovery-plus'],
    tvChannels: ['TNT Sports 1', 'Channel 4'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['TNT Sports', 'Channel 4'], streamingPlatforms: ['discovery-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['rugby', 'rugby-union', 'premiership', 'final', 'championship'],
    sessionType: 'final',
    isFeatured: true,
    importance: 'high',
  },

  // ──────────────── SATURDAY ────────────────
  {
    id: 'f1-canada-race-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'f1',
    league: 'Formula 1 World Championship',
    competition: 'Canadian Grand Prix',
    eventTitle: 'Canadian Grand Prix — Race',
    participants: [],
    stage: 'Race',
    startTimeUtc: fromNow(2 * 24 * 60 + 60),
    endTimeUtc: fromNow(2 * 24 * 60 + 240),
    status: 'upcoming',
    isLive: false,
    venue: 'Circuit Gilles Villeneuve, Montreal',
    country: 'Canada',
    broadcasters: getBroadcasters(['sky-sports-f1', 'channel-4']),
    streamingPlatforms: ['sky-sports-f1'],
    tvChannels: ['Sky Sports F1', 'Channel 4 (highlights)'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports F1', 'Channel 4'], streamingPlatforms: ['sky-sports-f1'] },
      { region: 'US', country: 'US', broadcasters: ['ESPN+'], streamingPlatforms: ['espn-plus'] },
      { region: 'Global', country: 'Global', broadcasters: ['F1 TV Pro'], streamingPlatforms: [] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['f1', 'race', 'grand-prix', 'canada', 'weekend'],
    seriesId: 'f1-canada-2026',
    sessionType: 'race',
    relatedEventIds: ['f1-canada-fp2-2026', 'f1-canada-qualifying-2026'],
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'golf-us-open-rd2-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'golf',
    league: 'US Open Golf',
    competition: 'US Open Championship 2026',
    eventTitle: 'US Open — Round 2',
    participants: [],
    stage: 'Round 2',
    startTimeUtc: fromNow(2 * 24 * 60 + 120),
    endTimeUtc: fromNow(2 * 24 * 60 + 480),
    status: 'upcoming',
    isLive: false,
    venue: 'Pinehurst Resort No. 2, North Carolina',
    country: 'US',
    broadcasters: getBroadcasters(['sky-sports', 'bbc-sport']),
    streamingPlatforms: ['peacock'],
    tvChannels: ['Sky Sports Golf', 'BBC Sport'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Golf', 'BBC Sport'], streamingPlatforms: [] },
      { region: 'US', country: 'US', broadcasters: ['Peacock', 'NBC'], streamingPlatforms: ['peacock'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['golf', 'major', 'us-open'],
    sessionType: 'other',
    importance: 'high',
  },
  {
    id: 'tennis-queens-final-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'tennis',
    league: 'ATP Tour',
    competition: "cinch Championships (Queen's Club)",
    eventTitle: "Queen's Club Final",
    participants: [],
    stage: 'Final',
    startTimeUtc: fromNow(2 * 24 * 60 + 180),
    endTimeUtc: fromNow(2 * 24 * 60 + 300),
    status: 'upcoming',
    isLive: false,
    venue: "Queen's Club, London",
    country: 'England',
    broadcasters: getBroadcasters(['amazon-prime']),
    streamingPlatforms: ['amazon-prime'],
    tvChannels: [],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Amazon Prime Video'], streamingPlatforms: ['amazon-prime'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['tennis', 'atp', 'queens', 'grass', 'final', 'wimbledon-prep'],
    sessionType: 'final',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'motogp-italy-race-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'motorsport',
    league: 'MotoGP World Championship',
    competition: 'Gran Premio d\'Italia Oakley',
    eventTitle: 'Italian MotoGP — Race',
    participants: [],
    stage: 'Race',
    startTimeUtc: fromNow(2 * 24 * 60 + 60),
    endTimeUtc: fromNow(2 * 24 * 60 + 150),
    status: 'upcoming',
    isLive: false,
    venue: 'Autodromo del Mugello',
    country: 'Italy',
    broadcasters: getBroadcasters(['itv4', 'sky-sports-main']),
    streamingPlatforms: ['discovery-plus'],
    tvChannels: ['ITV4', 'BT Sport 2'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['ITV4', 'BT Sport 2'], streamingPlatforms: ['discovery-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['motogp', 'motorsport', 'italy', 'mugello', 'race'],
    sessionType: 'race',
    importance: 'medium',
  },
  {
    id: 'cricket-eng-ind-test2-day3',
    source: 'mock',
    sourcePriority: 1,
    sport: 'cricket',
    league: 'International Cricket',
    competition: 'England vs India Test Series',
    eventTitle: 'England vs India — 2nd Test, Day 3',
    participants: [
      { name: 'England', shortName: 'ENG', nationality: 'England', isHome: true },
      { name: 'India', shortName: 'IND', nationality: 'India' },
    ],
    stage: 'Day 3',
    startTimeUtc: fromNow(2 * 24 * 60 + 30),
    endTimeUtc: fromNow(2 * 24 * 60 + 390),
    status: 'upcoming',
    isLive: false,
    venue: "Headingley, Leeds",
    country: 'England',
    broadcasters: getBroadcasters(['sky-sports', 'channel-4']),
    streamingPlatforms: ['sky-sports'],
    tvChannels: ['Sky Sports Cricket'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Cricket'], streamingPlatforms: ['sky-sports'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['cricket', 'test', 'international'],
    sessionType: 'test',
    relatedEventIds: ['cricket-eng-ind-test2-day1'],
    importance: 'medium',
  },

  // ──────────────── SUNDAY ────────────────
  {
    id: 'nfl-preseason-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'nfl',
    league: 'NFL',
    competition: 'NFL International Series (London)',
    eventTitle: 'Kansas City Chiefs vs Philadelphia Eagles — London Game',
    participants: [
      { name: 'Kansas City Chiefs', shortName: 'KC Chiefs' },
      { name: 'Philadelphia Eagles', shortName: 'Eagles' },
    ],
    stage: 'Regular Season — Week 1',
    startTimeUtc: fromNow(3 * 24 * 60 + 120),
    endTimeUtc: fromNow(3 * 24 * 60 + 300),
    status: 'upcoming',
    isLive: false,
    venue: "Tottenham Hotspur Stadium, London",
    country: 'England',
    broadcasters: getBroadcasters(['channel-4', 'bbc-one']),
    streamingPlatforms: [],
    tvChannels: ['Channel 4', 'BBC One'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Channel 4'], streamingPlatforms: [], isFree: true } as { region: string; country: string; broadcasters: string[]; streamingPlatforms: string[]; isGeolocked?: boolean },
      { region: 'US', country: 'US', broadcasters: ['NBC', 'CBS'], streamingPlatforms: ['peacock'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['nfl', 'american-football', 'london', 'international-series', 'free-to-air'],
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'golf-us-open-rd3-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'golf',
    league: 'US Open Golf',
    competition: 'US Open Championship 2026',
    eventTitle: 'US Open — Round 3 (Moving Day)',
    participants: [],
    stage: 'Round 3',
    startTimeUtc: fromNow(3 * 24 * 60 + 140),
    endTimeUtc: fromNow(3 * 24 * 60 + 500),
    status: 'upcoming',
    isLive: false,
    venue: 'Pinehurst Resort No. 2, North Carolina',
    country: 'US',
    broadcasters: getBroadcasters(['sky-sports', 'bbc-sport']),
    streamingPlatforms: ['peacock'],
    tvChannels: ['Sky Sports Golf', 'BBC Sport'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Golf', 'BBC Sport'], streamingPlatforms: [] },
      { region: 'US', country: 'US', broadcasters: ['Peacock', 'NBC'], streamingPlatforms: ['peacock'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['golf', 'major', 'us-open'],
    sessionType: 'other',
    importance: 'high',
  },
  {
    id: 'snooker-world-championship-final',
    source: 'mock',
    sourcePriority: 1,
    sport: 'snooker',
    league: 'World Snooker Tour',
    competition: 'World Grand Prix Snooker',
    eventTitle: 'Ronnie O\'Sullivan vs Judd Trump — World Grand Prix Final',
    participants: [
      { name: "Ronnie O'Sullivan", shortName: "O'Sullivan", nationality: 'England', rank: 1 },
      { name: 'Judd Trump', shortName: 'Trump', nationality: 'England', rank: 2 },
    ],
    stage: 'Final',
    startTimeUtc: fromNow(3 * 24 * 60 + 240),
    endTimeUtc: fromNow(3 * 24 * 60 + 480),
    status: 'upcoming',
    isLive: false,
    venue: 'Ricoh Arena, Coventry',
    country: 'England',
    broadcasters: getBroadcasters(['bbc-two', 'eurosport']),
    streamingPlatforms: ['discovery-plus'],
    tvChannels: ['BBC Two', 'Eurosport 1'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['BBC Two', 'Eurosport 1'], streamingPlatforms: [] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['snooker', 'final', 'free-to-air'],
    sessionType: 'final',
    importance: 'medium',
  },

  // ──────────────── NEXT WEEK ────────────────
  {
    id: 'wimbledon-day1-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'tennis',
    league: 'The Championships, Wimbledon',
    competition: 'Wimbledon 2026',
    eventTitle: 'Wimbledon 2026 — Day 1 (1st Round)',
    participants: [],
    stage: 'First Round',
    startTimeUtc: fromNow(7 * 24 * 60 + 30),
    endTimeUtc: fromNow(7 * 24 * 60 + 540),
    status: 'upcoming',
    isLive: false,
    venue: 'All England Lawn Tennis Club, Wimbledon',
    country: 'England',
    broadcasters: getBroadcasters(['bbc-one', 'bbc-two', 'amazon-prime']),
    streamingPlatforms: ['amazon-prime', 'bbc-sport'],
    tvChannels: ['BBC One', 'BBC Two'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['BBC One', 'BBC Two', 'Amazon Prime'], streamingPlatforms: [], isFree: true } as { region: string; country: string; broadcasters: string[]; streamingPlatforms: string[]; isGeolocked?: boolean },
      { region: 'US', country: 'US', broadcasters: ['ESPN'], streamingPlatforms: ['espn-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['tennis', 'wimbledon', 'grand-slam', 'grass', 'free-to-air', 'qualifying'],
    sessionType: 'match',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'cycling-tour-de-france-stage1',
    source: 'mock',
    sourcePriority: 1,
    sport: 'cycling',
    league: 'Tour de France',
    competition: 'Tour de France 2026',
    eventTitle: 'Tour de France — Stage 1',
    participants: [],
    stage: 'Stage 1',
    startTimeUtc: fromNow(8 * 24 * 60 + 120),
    endTimeUtc: fromNow(8 * 24 * 60 + 300),
    status: 'upcoming',
    isLive: false,
    venue: 'Florence, Italy',
    country: 'Italy',
    broadcasters: getBroadcasters(['itv4', 'eurosport']),
    streamingPlatforms: ['discovery-plus'],
    tvChannels: ['ITV4', 'Eurosport 1'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['ITV4', 'Eurosport 1'], streamingPlatforms: ['discovery-plus'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['cycling', 'tour-de-france', 'grand-tour'],
    sessionType: 'race',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'ipl-final-2026',
    source: 'mock',
    sourcePriority: 1,
    sport: 'cricket',
    league: 'Indian Premier League',
    competition: 'IPL 2026 Final',
    eventTitle: 'Mumbai Indians vs Chennai Super Kings — IPL Final',
    participants: [
      { name: 'Mumbai Indians', shortName: 'MI' },
      { name: 'Chennai Super Kings', shortName: 'CSK' },
    ],
    stage: 'Final',
    startTimeUtc: fromNow(5 * 24 * 60 + 90),
    endTimeUtc: fromNow(5 * 24 * 60 + 270),
    status: 'upcoming',
    isLive: false,
    venue: 'Narendra Modi Stadium, Ahmedabad',
    country: 'India',
    broadcasters: getBroadcasters(['sky-sports']),
    streamingPlatforms: [],
    tvChannels: ['Sky Sports Cricket'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Cricket'], streamingPlatforms: [] },
      { region: 'India', country: 'IN', broadcasters: ['Star Sports', 'Hotstar'], streamingPlatforms: [], isGeolocked: true },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['cricket', 't20', 'ipl', 'final', 'championship'],
    sessionType: 't20',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'golf-us-open-final-rd',
    source: 'mock',
    sourcePriority: 1,
    sport: 'golf',
    league: 'US Open Golf',
    competition: 'US Open Championship 2026',
    eventTitle: 'US Open — Final Round (Sunday)',
    participants: [],
    stage: 'Final Round',
    startTimeUtc: fromNow(4 * 24 * 60 + 150),
    endTimeUtc: fromNow(4 * 24 * 60 + 510),
    status: 'upcoming',
    isLive: false,
    venue: 'Pinehurst Resort No. 2, North Carolina',
    country: 'US',
    broadcasters: getBroadcasters(['sky-sports', 'bbc-sport']),
    streamingPlatforms: ['peacock'],
    tvChannels: ['Sky Sports Golf', 'BBC Sport'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Golf', 'BBC Sport'], streamingPlatforms: [] },
      { region: 'US', country: 'US', broadcasters: ['Peacock', 'NBC'], streamingPlatforms: ['peacock'] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['golf', 'major', 'us-open', 'final-round'],
    sessionType: 'other',
    isFeatured: true,
    importance: 'high',
  },
  {
    id: 'athletics-diamond-league-oslo',
    source: 'mock',
    sourcePriority: 1,
    sport: 'athletics',
    league: 'Wanda Diamond League',
    competition: 'Diamond League — Oslo (Bislett Games)',
    eventTitle: 'Bislett Games — Diamond League Oslo',
    participants: [],
    stage: 'Diamond League Meeting',
    startTimeUtc: fromNow(6 * 24 * 60 + 240),
    endTimeUtc: fromNow(6 * 24 * 60 + 360),
    status: 'upcoming',
    isLive: false,
    venue: 'Bislett Stadium, Oslo',
    country: 'Norway',
    broadcasters: getBroadcasters(['bbc-sport', 'eurosport']),
    streamingPlatforms: ['discovery-plus'],
    tvChannels: ['BBC Sport', 'Eurosport'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['BBC Sport', 'Eurosport'], streamingPlatforms: [] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'medium',
    tags: ['athletics', 'diamond-league', 'track-and-field'],
    importance: 'medium',
  },
  {
    id: 'darts-premier-league-final',
    source: 'mock',
    sourcePriority: 1,
    sport: 'darts',
    league: 'PDC',
    competition: 'Premier League Darts — Night 16',
    eventTitle: 'Premier League Darts — Night 16 (Final 4)',
    participants: [],
    stage: 'Night 16 — Finals Night',
    startTimeUtc: fromNow(4 * 24 * 60 + 300),
    endTimeUtc: fromNow(4 * 24 * 60 + 420),
    status: 'upcoming',
    isLive: false,
    venue: 'The O2 Arena, London',
    country: 'England',
    broadcasters: getBroadcasters(['sky-sports-main']),
    streamingPlatforms: [],
    tvChannels: ['Sky Sports Action'],
    regionAvailability: [
      { region: 'UK', country: 'GB', broadcasters: ['Sky Sports Action'], streamingPlatforms: [] },
    ],
    lastUpdated: NOW.toISOString(),
    confidence: 'high',
    tags: ['darts', 'pdc', 'premier-league'],
    importance: 'medium',
  },
];

export function getEventsForDate(dateStr: string): SportEvent[] {
  return MOCK_EVENTS.filter(e => e.startTimeUtc.startsWith(dateStr));
}

export function getLiveEvents(): SportEvent[] {
  return MOCK_EVENTS.filter(e => e.isLive || e.status === 'live');
}

export function getUpcomingEvents(withinMinutes = 180): SportEvent[] {
  const cutoff = new Date(Date.now() + withinMinutes * 60 * 1000);
  const now = new Date();
  return MOCK_EVENTS.filter(e => {
    const start = new Date(e.startTimeUtc);
    return !e.isLive && start > now && start <= cutoff;
  });
}

export function getFeaturedEvents(): SportEvent[] {
  return MOCK_EVENTS.filter(e => e.isFeatured);
}
